http:
  host: localhost
  port: 3000
log:
  level: 'info'
  filename: '/tmp/jrm.log'
databases:
  tags: 'tests/data/temp-dbs/tags'
  tickets: 'tests/data/temp-dbs/tickets'
jira:
  host: 'kairion.atlassian.net'
  epicsKey: 'customfield_10500'
  newCapKey: 'customfield_13103'
  username: 'your_username'
  password: 'your_password'
# alternatively, use oath to authorize. Delete both fields username and password. The old access data:
#    oauth:
#      consumer_key: '94S37YKpXdmmbENb'
#      consumer_secret: '/.ssh/jira_rsa' # use path relative to home path
#      access_token: 'VnBpdujgzdSHtJnTOXSY6xfqml2Y6NZg'
#      access_token_secret: 'nhclzMeidDRZiAOeVyIa0BI5CtAe3Kk2'
git:
  featurePrefix: 'refs/heads/feature/'
  repositories:
    testgit:
      path: './tests/data/repositories/testrepo1/.git'
      name: 'testgit'
webhooks:
  jira:
    update-ticket:
      path: '../webhooks/update-ticket'
      params:
        dbName: 'tickets'
