http:
  host: localhost
  port: 3000
log:
  releasemanager:
    level: 'info'
    filename: 'jrm.log'
  webhooks:
    level: 'info'
    filename: 'webhooks.log'
databases:
  tags: 'tests/data/temp-dbs/tags'
  tickets: 'tests/data/temp-dbs/tickets'
  webhooks: 'tests/data/temp-dbs/webhooks-data'
jira:
  host: 'kairion.atlassian.net'
  epicsKey: 'customfield_10500'
  newCapKey: 'customfield_13103'
  username: 'your_username'
  password: 'your_password'
  issueType:
    epic: '5'
    deployment: '11301'
    codeReview: '11305'
    functionalReview: '9'
    roadmapPlanning: '10500'
  status:
    notPlanned: '10307'
    selectedForDevelopment: '10908'
    deployed: '5'
  transition:
    selectedForDevelopment: '911'
    deployed: '941'
# alternatively, use oath to authorize. Delete both fields username and password. The old access data:
#    oauth:
#      consumer_key: '94S37YKpXdmmbENb'
#      consumer_secret: '/.ssh/jira_rsa' # use path relative to home path
#      access_token: 'VnBpdujgzdSHtJnTOXSY6xfqml2Y6NZg'
#      access_token_secret: 'nhclzMeidDRZiAOeVyIa0BI5CtAe3Kk2'
git:
  featurePrefix: 'refs/heads/feature/'
  repositories:
    testgit:
      path: './tests/data/repositories/testrepo1/.git'
      name: 'testgit'
webhooks:
  jira:
    logger-issue-updated:
      path: '../webhooks/logger-issue-updated'
    update-ticket:
      path: '../webhooks/update-ticket'
      params:
        dbName: 'tickets'
    create-auxiliary-tickets:
      path: '../webhooks/create-auxiliary-tickets'
    tickets-to-development:
      path: '../webhooks/tickets-to-development'
    develop-on-timetracking:
      path: '../webhooks/develop-on-timetracking'
  bitbucket:
    create-tag:
      path: '../webhooks/create-tag'
